### ISSUE TITLE
Unable to compile nchan with NGINX 1.23.0 mainline...

### ISSUE THREAD

**Issue by GerritS76** [slact/nchan#641]
Have been trying to compile nchan with NGINX 1.23.0 but unfortunately it fails everytime.
[nginx-comptile-error.txt](https://github.com/slact/nchan/files/8985354/nginx-comptile-error.txt)

**Comment by tflin** [comment]
That is the pull request https://github.com/slact/nchan/pull/634 trying solve. @slact Please help to merge it, thanks.

**Comment by plinss** [comment]
I'm unable to build with Nginx 1.23.0 and the current version (with PR #634 merged). This looks like an issue introduced in 49b029cb275433a67b193b505ab999d1831883de

```
-o objs/addon/memory/ipc.o \
	/build/nginx-1.23.0/debian/modules/nchan/src/store/memory/ipc.c
/build/nginx-1.23.0/debian/modules/nchan/src/store/memory/ipc.c: In function 'ipc_worker_slots':
/build/nginx-1.23.0/debian/modules/nchan/src/store/memory/ipc.c:64:22: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
   64 |   *workerslots_array = ipc->worker_slots;
      |                      ^
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:2796: objs/addon/memory/ipc.o] Error 1
```

**Comment by slact** [comment]
the discarded qualifiers warning has been fixed as of 1a67d07ffd4fe7971fc2064b53430eb6f6eee514

**Comment by slact** [comment]
Closing this issue as the PR has been merged and it builds fine now.
