### ISSUE TITLE
compile error after 0a8e691

### ISSUE THREAD

**Issue by bymaximus** [slact/nchan#239]
Getting compile error after updated latest source (related to 0a8e6911f2b829b5cc4c808c98f9437bd633fef3)

```
/root/nchan/src/store/spool.c: In function ‘its_time_for_a_spooling’:
/root/nchan/src/store/spool.c:1014:3: error: implicit declaration of function ‘validate_spool’ [-Werror=implicit-function-declaration]
   validate_spool(spool);
   ^
```

**Comment by slact** [comment]
oops, that wasn't supposed to make it into the commit. fixed in 32f1950
