### ISSUE TITLE
Should not use `for loop declarations`

### ISSUE THREAD

**Issue by sergey-dryabzhinsky** [slact/nchan#628]
gcc-4.8 in Ubuntu 14.04 fails in `hiredis` code with:
```
/home/sergey/debuild/nginx/nginx-1.20/nginx/nginx-1.20.2/debian/modules/http-nchan/src/store/redis/hiredis/read.c: In function ‘redisReaderFree’:
/home/sergey/debuild/nginx/nginx-1.20/nginx/nginx-1.20.2/debian/modules/http-nchan/src/store/redis/hiredis/read.c:646:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (int i = 0; i < r->tasks; i++) {
         ^
```

I think that can be healed via CFLAGS declaration in `config`.
Just add these lines after `have= ...`:
```
CFLAGS="$CFLAGS -std=c99"
```
This should work fine with gcc-4.4+

Or move `i` declaration from loop if you're supporting `hiredis` code.
