### ISSUE TITLE
Bug on event sent

### ISSUE THREAD

**Issue by valydvweb** [slact/nchan#220]
Hello Leo,

I did a test configuration like this:

    location = "/test" {        
            nchan_channel_events_channel_id "events";
            nchan_pubsub;
            nchan_channel_id "test";
            nchan_message_buffer_length 30;
            nchan_message_timeout 1m;
            nchan_subscriber_first_message newest;
     }

    location = "/events" {
            nchan_channel_group "meta";
            nchan_pubsub;
            nchan_channel_id "events";
            nchan_message_buffer_length 30;
            nchan_message_timeout 1m;
     }

I did tests using HTML5 WebSockets

when connected .. i receive
subscriber_enqueue test

when disconnected .. i receive
subscriber_dequeue test

BUT when i sent first message .. i receive
subscriber_enqueue test
(one time)

Thank's,
Valy

**Comment by slact** [comment]
message publication events exist, but are currently disabled. As I recall, subscriber deque/enqueue and channel deletion events are all that is published on the events channel.

**Comment by valydvweb** [comment]
OK, but is another problem:

subscriber_enqueue {channel_id} is called incorrectly (for two times)

For first time is called correctly (when establishing connection)

But .. next time is called when the user post message

I tested using HTML5 Websocket.
    
    window.onload = function() {

        var cn = new WebSocket('ws://my-host/test'),
        msg = document.getElementById('msg');
	
        cn.onopen = function() {
            console.log('Open test connection'); // in this point is called subscriber_enqueue test
        }

       cn.onmessage = function(e) {
            console.log('Receiving test message: ' + e.data);
       }

        msg.addEventListener('keypress', function(e) {
            if (e.which == 13 || e.keyCode == 13) {
                e.preventDefault();
                cn.send(msg.value.trim()); // subscriber_enqueue test is called again (on send message)
            }
        });
    }

Thank's

**Comment by valydvweb** [comment]
publication event is not very important but subscribers_enqueue and dequeue is important to called correctly.

**Comment by slact** [comment]
I can't reproduce this. Can you show me your full Nginx config?

**Comment by valydvweb** [comment]
Sure.

My NGINX version is 1.10.1

My NGINX text configuration:
-----------------------------------

    worker_processes 1;

    events {
        worker_connections  1024;
        accept_mutex off;
    }

    worker_rlimit_core  500M;
    working_directory   /etc/nginx/cores/;

    http {

        include       mime.types;
        default_type  application/octet-stream;
        client_max_body_size 50M;
        keepalive_timeout 65;

        # NCHAN COMMON
      nchan_max_reserved_memory 32M;
      nchan_redis_url "redis://127.0.0.1:6379";
      nchan_use_redis on;

    server {
        
        listen       80;
        server_name  localhost;

         #charset utf-8
         location / {
             root   /home/www;
             index  index.html index.htm;
          }

           location = "/test" {
                nchan_channel_events_channel_id "events";
                nchan_pubsub;
                nchan_channel_id "test";
                nchan_message_buffer_length 30;
                nchan_message_timeout 1m;
                nchan_subscriber_first_message newest;
            }

            location = "/events" {
                nchan_channel_group "meta";
                nchan_pubsub;
                nchan_channel_id "events";
                nchan_message_buffer_length 30;
                nchan_message_timeout 1m;
            }
         }
    }

Thank's

**Comment by valydvweb** [comment]
Hello Leo,

Any progress width this problem?
You have reproduced this?
Can I help you with something?

Thank's

**Comment by slact** [comment]
Found it. Fixed in c45cb72 .

**Comment by valydvweb** [comment]
Thank's , but I have a compile error:

cc1: warnings being treated as errors
/root/nchan/src/store/redis/rdsstore.c: In function 'redisChannelDeleteCallback':
/root/nchan/src/store/redis/rdsstore.c:1817: error: 'rdata' may be used uninitialized in this function
make[1]: *** [objs/addon/redis/rdsstore.o] Error 1
make[1]: Leaving directory `/root/nginx-1.10.1'
make: *** [build] Error 2

**Comment by slact** [comment]
Wow dude, your compiler is  borderline retarded. I'm not even seeing this using (my version of) GCC5, and it's obviously incorrect if you look at the code.  Fixed in 0f767df.

**Comment by valydvweb** [comment]
Hello again,

My GCC version is 4.4.7 (for CentOS 6.7). 
I think you have a newer version.
But this version is standard for CentOS 6

Sorry for this bad problem and
Thank you very much

I tested and everything is OK

Thank's :)

**Comment by slact** [comment]
: )
