### ISSUE TITLE
Unable to compile with Nginx 25.3

### ISSUE THREAD

**Issue by theonlyzby** [slact/nchan#681]
I am trying to compile wih NGINX 25.3 (Openresy 25.3.1) on a Aarch64 Debian Bookworm , I get the following errors:

  /opt/openresty-1.25.3.1/../nchan-1.3.6/src/subscribers/websocket.c:852:21: error: ‘permessage_deflate_t’ has no member named ‘zstream_in’
  852 |     if(fsub->deflate.zstream_in) {
      |                     ^

Do you know how I could fix this, please?
Any help is welcome, thank you in advance!

**Comment by slact** [comment]
The issue is that Nchan expects the zlib module to be built. but for some reason it's not detecting it. What exactly is your build process?

**Comment by slact** [comment]
stale
